# Generated by Django 2.0.1 on 2018-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile-image/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
