# Generated by Django 2.0.1 on 2018-02-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creator',
            new_name='user',
        ),
    ]
